language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install

script: vendor/bin/phpspec run -f pretty -v
